# adapted from https://github.com/r-lib/actions/tree/master/examples#test-coverage-workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      COVERAGE: "true"
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.5"

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: jasp-stats/jasp-actions/setup-test-env@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          # Rstudio's binary crashes hard
          install.packages("igraph", type = "source", repos = "https://cloud.r-project.org/")
          # temporarily!
          remotes::install_github("vandenman/jaspTools@support_binary_pkgs")
          jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

